#-------------------------------
# General Site Settings
title: Personal Site
logo: Q_logo.svg # You can add own logo.


#-------------------------------
# Author Settings
author:
  name: Qi Wu
  image: 01.jpg
  say-hello: Hello, Iâ€™m <strong>Qi Wu</strong>
  bio: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.



