#-------------------------------
# General Site Settings
title: Qi’s Page
logo: Qi_logo.png # You can add own logo.


#-------------------------------
# Author Settings
author:
  name: Qi Wu
  image: post_summer_school.jpg
  say-hello: Hello, I’m <strong>Qi Wu</strong>
  title: Ph.D. candidate of KU Leuven & IMEC
  bio: Surface science and optical metrology researcher with expertise in surface modification, ATR-FTIR spectroscopy, and optical simulations. 4+ years of hands‑on cleanroom experience and a strong record of building experimental platforms & integrating hardware-software pipelines. Actively interested in how machine learning will be integrated into future tasks.

#-------------------------------
# Contact links
linkedin: https://linkedin.com/in/qi-wu-5b57261b2/ # Add your Twitter handle

